"""Server configuration shared by local commands and runtime startup."""
import json
import os
from pathlib import Path

from qmt_rpyc.adapters.registry import DEFAULT_ADAPTER, select_adapter


def default_server_dir():
    base = os.environ.get("LOCALAPPDATA")
    if base:
        return Path(base) / "qmt-rpyc"
    return Path.home() / ".qmt-rpyc"


def default_config_path():
    return default_server_dir() / "config.env"


def env_defaults():
    """Runtime defaults; init deliberately writes a loopback host by default."""
    return {
        "QMT_RPYC_HOST": "0.0.0.0",
        "QMT_RPYC_PORT": "18812",
        "QMT_RPYC_AUTH_KEY": "",
        "QMT_RPYC_ADAPTER": DEFAULT_ADAPTER,
        "QMT_RPYC_BIGQMT_PIPE": "qmt_rpyc_bridge_v1",
        "QMT_RPYC_BIGQMT_TIMEOUT": "30",
        "QMT_RPYC_CACHE_PATH": "",
        "QMT_RPYC_CACHE_SOURCE": "",
        "QMT_RPYC_CACHE_POLICIES": "{}",
        "QMT_RPYC_DEBUG": "0",
        "QMT_RPYC_ALLOW_INSECURE": "0",
        "QMT_PATH": "",
        "QMT_XTQUANT_PATH": "",
        "QMT_SESSION_ID": "1",
        "QMT_ACCOUNT_ID": "",
        "QMT_RPYC_TLS_KEY": "",
        "QMT_RPYC_TLS_CERT": "",
        "QMT_RPYC_TLS_CA": "",
        "QMT_HEARTBEAT_INTERVAL": "30",
        "QMT_HEARTBEAT_TIMEOUT": "5",
        "QMT_HEARTBEAT_MAX_FAILURES": "3",
        "QMT_RECONNECT_MAX_ATTEMPTS": "0",
        "QMT_BATCH_MAX_WORKERS": "8",
        "QMT_RPYC_LOG_DIR": str(default_server_dir() / "logs"),
    }


def valid_auth_key(value):
    return isinstance(value, str) and bool(value.strip()) and value != "your-secret-key-here"


def read_env(path):
    path = Path(path)
    if not path.exists():
        return {}
    try:
        from dotenv import dotenv_values
        return {
            key: value for key, value in dotenv_values(str(path)).items()
            if value is not None
        }
    except ImportError:
        values = {}
        for line in path.read_text(encoding="utf-8-sig").splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            values[key.strip()] = value.strip().strip("\"'")
        return values


def write_env(path, values):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    defaults = env_defaults()
    defaults["QMT_RPYC_HOST"] = "127.0.0.1"
    lines = [
        "# qmt-rpyc server configuration",
        "# Generated by qmt-rpyc-server init",
    ]
    for key, default in defaults.items():
        value = values.get(key, default)
        lines.append("{}={}".format(
            key, json.dumps(str(value), ensure_ascii=False)
        ))
    temp = path.with_suffix(path.suffix + ".tmp")
    temp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    temp.replace(path)
    return path


def _integer(values, name, minimum, maximum=None):
    raw = values[name]
    try:
        value = int(raw)
    except ValueError as e:
        raise ValueError(f"{name} must be an integer, got {raw!r}") from e
    if value < minimum or (maximum is not None and value > maximum):
        if maximum is None:
            expected = f">= {minimum}"
        else:
            expected = f"between {minimum} and {maximum}"
        raise ValueError(f"{name} must be {expected}, got {value}")
    return value


def _env_bool(name, default=False):
    raw = os.environ.get(name)
    if raw is None:
        return default
    normalized = raw.strip().lower()
    if normalized in ("1", "true", "yes", "on"):
        return True
    if normalized in ("0", "false", "no", "off"):
        return False
    raise ValueError(f"{name} must be a boolean, got {raw!r}")


def load_config(config_path=None):
    from dotenv import load_dotenv
    path = Path(config_path) if config_path else default_config_path()
    load_dotenv(str(path), override=False)
    values = env_defaults()
    values.update(os.environ)
    return {
        "host": values["QMT_RPYC_HOST"],
        "port": _integer(values, "QMT_RPYC_PORT", 1, 65535),
        "auth_key": os.environ.get("QMT_RPYC_AUTH_KEY"),
        "allow_insecure": _env_bool("QMT_RPYC_ALLOW_INSECURE"),
        "debug": _env_bool("QMT_RPYC_DEBUG"),
        "cache_path": values["QMT_RPYC_CACHE_PATH"],
        "cache_source": values["QMT_RPYC_CACHE_SOURCE"],
        "cache_policies": values["QMT_RPYC_CACHE_POLICIES"],
        "adapter": values["QMT_RPYC_ADAPTER"],
        "bigqmt_pipe": values["QMT_RPYC_BIGQMT_PIPE"],
        "bigqmt_timeout": _integer(values, "QMT_RPYC_BIGQMT_TIMEOUT", 1, 120),
        "qmt_path": values["QMT_PATH"],
        "xtquant_path": values["QMT_XTQUANT_PATH"],
        "qmt_session_id": _integer(values, "QMT_SESSION_ID", 0),
        "qmt_account_id": values["QMT_ACCOUNT_ID"],
        "tls_keyfile": os.environ.get("QMT_RPYC_TLS_KEY"),
        "tls_certfile": os.environ.get("QMT_RPYC_TLS_CERT"),
        "tls_ca_certs": os.environ.get("QMT_RPYC_TLS_CA"),
        "log_dir": values["QMT_RPYC_LOG_DIR"],
        "config_path": str(path),
        "heartbeat_interval": _integer(values, "QMT_HEARTBEAT_INTERVAL", 1),
        "heartbeat_timeout": _integer(values, "QMT_HEARTBEAT_TIMEOUT", 1),
        "heartbeat_max_failures": _integer(values, "QMT_HEARTBEAT_MAX_FAILURES", 1),
        "reconnect_max_attempts": _integer(values, "QMT_RECONNECT_MAX_ATTEMPTS", 0),
    }


def validate_config(cfg):
    from qmt_rpyc.storage.policy import StorageConfig
    StorageConfig.from_config(cfg, default_server_dir())
    adapter = select_adapter(cfg.get("adapter", DEFAULT_ADAPTER))
    if not adapter.requires_native_sdk:
        from qmt_rpyc.adapters.bigqmt.winpipe import pipe_path
        pipe_path(cfg.get("bigqmt_pipe", "qmt_rpyc_bridge_v1"))
    auth_key = cfg.get("auth_key")
    if not valid_auth_key(auth_key) and not cfg.get("allow_insecure", False):
        raise ValueError(
            "QMT_RPYC_AUTH_KEY must be non-empty and not use the placeholder; "
            "set "
            "QMT_RPYC_ALLOW_INSECURE=1 only for an isolated test environment")
    if bool(cfg.get("tls_keyfile")) != bool(cfg.get("tls_certfile")):
        raise ValueError(
            "QMT_RPYC_TLS_KEY and QMT_RPYC_TLS_CERT must be configured together")
