#!/usr/bin/env python3
"""Build a standalone Python 3.6 QMT strategy from the owned bridge modules."""
import argparse
import ast
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODULES = ('financial_wire.py', 'bridge_debug.py', 'bridge_trading.py', 'bridge_runtime.py', 'bridge_queue.py', 'winpipe.py')
ENTRY = '''

# Trading uses the account supplied in each authenticated request.
PIPE_NAME = "qmt_rpyc_bridge_v1"
_service = None
_bridge = None


def init(ContextInfo):
    global _service, _bridge
    from datetime import datetime, timedelta
    if _service is not None:
        raise RuntimeError("Bridge already initialized; stop the previous strategy")
    _bridge = BridgeQueue(StrategyRuntime(ContextInfo, globals()))
    _service = PipeServer(PIPE_NAME, _bridge)
    try:
        start = (datetime.now() + timedelta(seconds=1)).strftime("%Y-%m-%d %H:%M:%S")
        ContextInfo.run_time("bigqmt_bridge_pump", "100nMilliSecond", start)
        _service.start()
    except Exception:
        stop(ContextInfo)
        raise
    print("QMT_RPYC_BRIDGE ready; version=" + RELEASE_VERSION + "; build=" + STRATEGY_BUILD + "; read_only=False")


def bigqmt_bridge_pump(ContextInfo):
    if _service is None or _bridge is None:
        return
    # Pipe I/O and business dispatch share this callback: QMT schedules
    # background Python threads too rarely to carry a round trip. An
    # unhandled exception can stop the whole strategy, so it never propagates.
    try:
        _service.poll()
        _bridge.pump()
        _service.poll()
    except Exception:
        import traceback
        traceback.print_exc()


def handlebar(ContextInfo):
    pass


def stop(ContextInfo):
    global _service, _bridge
    if _service is not None:
        _service.stop()
    _service, _bridge = None, None
    print("QMT_RPYC_BRIDGE stopped; pending_handles_retained=" + str(reap()))
'''


def build():
    parts = ['# coding: gbk\n# QMT 策略文件：使用 GBK 编码。\n# Generated by scripts/build_bigqmt_strategy.py; edit the source modules.\n']
    for name in MODULES:
        source = (ROOT / 'src/qmt_rpyc/adapters/bigqmt' / name).read_text(encoding='utf-8')
        lines = source.splitlines(keepends=True)
        tree = ast.parse(source)
        for node in reversed(tree.body):
            if isinstance(node, ast.ImportFrom) and node.level:
                del lines[node.lineno - 1:node.end_lineno]
        parts.append('\n# ---- ' + name + ' ----\n' + ''.join(lines))
    version_tree = ast.parse((ROOT / 'src/qmt_rpyc/version.py').read_text(encoding='utf-8'))
    version = next(ast.literal_eval(node.value) for node in version_tree.body
                   if isinstance(node, ast.Assign)
                   and any(isinstance(target, ast.Name) and target.id == '__version__'
                           for target in node.targets))
    parts.insert(1, 'RELEASE_VERSION = ' + repr(version) + '\n')
    source = '\n'.join(parts) + ENTRY
    # Deterministic fingerprint of the generated source before adding itself.
    digest = hashlib.sha256(source.encode('gbk')).hexdigest()[:16]
    parts.insert(2, 'STRATEGY_BUILD = ' + repr(digest) + '\n')
    source = '\n'.join(parts) + ENTRY
    ast.parse(source, feature_version=(3, 6))
    return source


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(build().encode('gbk'))
    print(args.output)


if __name__ == '__main__':
    main()
