"""Human documentation, deliberately excluded from the wire contract hash.

Names and types come from operations/schema; these descriptions explain their
meaning. Missing documentation is an error, checked across every public model.
"""

OPERATION_DESCRIPTIONS = {
    'reference.list_sectors': '列出可查询的板块名称。',
    'reference.get_sector_members': '获取指定板块的合约代码。',
    'reference.get_dividend_events': '获取按日期排列的分红除权事件及事件比率。',
    'reference.get_index_weights': '获取指数成分及源端权重。',
    'instruments.list_option_underlyings': '列出当前期权标的代码；名称另查合约详情。',
    'instruments.get_details': '批量获取合约静态资料、名称、日期和股本。',
    'instruments.get_trading_reference': '批量获取涨跌停价、价格步长及交易参考值。',
    'options.get_expiry_dates': '获取标的当前尚未到期的期权到期日（含今天）。',
    'options.get_option_chain': '按标的和到期日获取当前期权合约代码。',
    'options.get_contract_details': '批量获取期权名称、标的、行权价、类型与单位。',
    'market.get_ticks': '批量获取最新报价、成交量、持仓量及买卖档位。',
    'market.get_market_ticks': '获取指定沪深市场的报价快照，按代码排序。',
    'market.get_daily_bars': '查询源端已缓存的日线；需要时先下载历史。',
    'market.get_intraday_bars': '查询源端已缓存的分钟/小时线；需要时先下载历史。',
    'market.get_trading_dates': '按市场查询交易日历。',
    'financials.get_reports': '按合约和日期查询固定字段的财务报表。',
    'downloads.start_history': '创建历史行情下载任务，返回任务引用。',
    'downloads.start_financials': '创建财务数据下载任务，返回任务引用。',
    'downloads.start_sectors': '创建板块资料下载任务，返回任务引用。',
    'downloads.start_index_weights': '创建指数权重下载任务，返回任务引用。',
    'downloads.get_task': '查询任务状态、进度和失败原因。',
    'trading.get_asset': '查询账户资金、冻结资金与资产市值。',
    'trading.list_positions': '查询账户持仓数量及可用数量。',
    'trading.list_orders': '查询账户委托、状态及累计成交信息。',
    'trading.submit_order': '提交买卖委托；受理不等于成交，不确定结果禁止重试。',
    'trading.cancel_order': '按委托标识发出撤单请求；成功不等于最终已撤。',
    'system.get_health': '查询服务版本、Trader 连接、重连及下载任务状态。',
    'system.get_capabilities': '查询每项固定 API 的源端适配可用性和原因。',
}

# Shared field meanings; model-specific exceptions are explicit below.
FIELD_DESCRIPTIONS = {
    'codes': '合约代码数组，保留券商后缀；最多 500 个、不可重复；空数组允许。',
    'code': '合约代码，保留券商后缀；不可为空或带首尾空白。',
    'underlying': '标的合约代码，例如 510050.SH，保留券商后缀。',
    'instrument': '合约代码，保留券商后缀。',
    'name': '源端合约名称，原样保留。',
    'market': '交易市场：SH（上海）或 SZ（深圳）。',
    'markets': '沪深市场数组，非空且不可重复。',
    'sector': '完整板块名称，可从 reference.list_sectors 获取。',
    'index': '指数代码，例如 000300.SH。',
    'start': '起始边界，含端点；null 表示不限制。日期用 YYYY-MM-DD，时间须含时区。',
    'end': '结束边界，含端点；null 表示不限制；不能早于 start。日期用 YYYY-MM-DD，时间须含时区。',
    'count': '最多返回的记录数量，正整数；与 start 互斥；null 表示范围内全部。',
    'period': 'K 线周期：m 为分钟、h 为小时、d 为日；允许值见类型。',
    'adjustment': '复权方式：none 不复权，front/back 前/后复权，front_ratio/back_ratio 等比前/后复权。',
    'fill_data': '将是否填充缺失行情的选项传给源端；不保证覆盖范围或新鲜度。',
    'rows': '按时间严格递增、不重复的 K 线记录；未下载缓存时可能为空。',
    'items': '逐合约成功或失败结果；每个请求代码对应一项，保留请求顺序。',
    'value': '该合约成功返回的类型化数据。',
    'error': '结构化失败原因。',
    'error_type': '固定错误类别，允许值见类型；不得仅凭消息文字推断执行结果。',
    'message': '可读说明；不作为稳定的机器判断字段。',
    'status': '结果或运行状态，允许值见类型。',
    'kind': '结果分支或任务种类的判别字段，允许值见类型。',
    'reason': '不可用或拒绝原因；不存在时为 null（若类型允许）。',
    'operation': '完整 API 名称，例如 market.get_ticks。',
    'contract_version': '固定请求/返回契约的版本号。',
    'phase': '失败发生阶段：执行前、派发、SDK 执行、结果校验或传输。',
    'outcome': '执行确定性；unknown 表示结果不明，写操作不可自动重试。',
    'request_id': '本次 RPC 请求关联标识。',
    'observed_at': '报价的源端时间，含时区；JSON 使用 UTC ISO 8601。',
    'last_price': '最新价格，不作应用层四舍五入。',
    'open': '开盘价；类型允许 null 时表示源数据缺失。',
    'high': '最高价；类型允许 null 时表示源数据缺失。',
    'low': '最低价；类型允许 null 时表示源数据缺失。',
    'close': '收盘价；null 表示源数据缺失。',
    'previous_close': '前收盘价；类型允许 null 时表示源数据缺失。',
    'turnover': '源端成交金额，不换算单位。',
    'settlement_price': '源端结算价，保留零值。',
    'previous_settlement_price': '源端前结算价，用于期权估值等计算。',
    'volume': '源端成交量整数；保留源端单位，不自行进行手/股换算。',
    'source_volume_detail': '源端 pvolume 数量字段，保持其原始口径。',
    'source_trading_status': '源端 stockStatus 整数状态码。',
    'open_interest': '源端持仓量整数。',
    'ask_prices': '卖盘各档价格，保持源端顺序和档位数；零值不删除。',
    'bid_prices': '买盘各档价格，保持源端顺序和档位数；零值不删除。',
    'ask_volumes': '卖盘各档数量，保持源端顺序和单位。',
    'bid_volumes': '买盘各档数量，保持源端顺序和单位。',
    'trade_date': '上海交易日，YYYY-MM-DD；不是 UTC 日期。',
    'source_time': '源端原始 K 线时间转换后的含时区时间；缺失为 null。',
    'bar_at': '日内 K 线时间，必须含时区；JSON 使用 UTC ISO 8601。',
    'source_suspension_flag': '源端 suspendFlag 停牌标记。',
    'market_date': '服务端本次查询采用的上海市场日期。',
    'dates': '去重升序的当前到期日，均不早于 market_date；不支持历史发现。',
    'contract_codes': '去重、排序后的当前期权代码；详情与报价通过其他 API 查询。',
    'option_type': '期权类型：CALL 看涨、PUT 看跌。',
    'expiry_date': '合约到期日期；静态资料中的占位日期通过 SourceDate 分支保留。',
    'strike_price': '行权价格，正数；不取整或四舍五入。',
    'contract_unit': '每张期权对应的标的数量，正整数；保留调整合约的实际单位。',
    'raw': '源端日期占位字符串，原样保留，不猜测有效日期。',
    'source_exchange': '源端 ExchangeID 交易所标识。',
    'source_instrument_id': '源端 InstrumentID 合约标识。',
    'created_date': '合约创建日期；真实日期与源端占位值分支表示。',
    'listed_date': '上市日期；真实日期与源端占位值分支表示。',
    'float_volume': '源端流通数量，不改变单位。',
    'total_volume': '源端总数量，不改变单位。',
    'source_volume_multiple': '源端 VolumeMultiple 数量乘数，不替代期权 contract_unit。',
    'delivery_end_date': '交割结束日期；源端不提供时为 null。',
    'source_is_trading': '源端是否可交易标记。',
    'upper_limit': '涨停价格。',
    'lower_limit': '跌停价格。',
    'price_tick': '最小报价价格步长。',
    'event_date': '除权除息事件的上海市场日期。',
    'source_event_at': '源端事件时间，转换为含时区时间。',
    'dr': '当次除权事件比率，不是累计复权因子；不能当作累计值使用。',
    'interest': '源端每股现金分红字段。',
    'stock_bonus': '源端送股字段，不改变口径。',
    'stock_gift': '源端转增股字段，不改变口径。',
    'allotment_quantity': '源端配股数量字段。',
    'allotment_price': '源端配股价格字段。',
    'source_gugai': '源端 gugai 股改字段，原样保留。',
    'weights': '成分代码到权重的映射；权重保持源端数值，不归一化。',
    'account': '账户标识，作为不透明字符串传递，不可转为整数。',
    'source_account_type': '源端账户类型整数码。',
    'cash': '可用资金。',
    'frozen_cash': '冻结资金。',
    'market_value': '源端证券市值。',
    'total_asset': '源端总资产。',
    'quantity': '数量整数；下单必须为正，持仓可以为零，单位遵循源端。',
    'available_quantity': '可用持仓数量，介于零与 quantity 之间。',
    'frozen_volume': '冻结持仓数量。',
    'on_road_volume': '在途持仓数量。',
    'yesterday_volume': '昨日持仓数量。',
    'open_price': '源端持仓成本/开仓价格字段。',
    'order_id': '委托标识，不透明字符串；保留原值，不假设可转为整数。',
    'exchange_order_id': '交易所委托标识，不透明字符串。',
    'submitted_at': '提交时间，含时区；JSON 使用 UTC ISO 8601。',
    'side': '方向：BUY 买、SELL 卖；查询结果可为 UNKNOWN。',
    'source_order_type': '源端委托方向/类型整数码。',
    'pricing': '委托定价方式；当前提交仅支持 LATEST_PRICE，查询可返回 UNKNOWN。',
    'source_price_type': '源端委托价格类型整数码。',
    'price': '传入源端的委托价格，必须非负；实际含义由 pricing 决定。',
    'submitted_price': '源端记录的委托价格。',
    'requested_quantity': '委托数量整数。',
    'filled_quantity': '累计成交数量，不能超过委托数量。',
    'average_fill_price': '累计成交均价；未成交可为零，已成交须为正。',
    'source_status': '源端委托状态整数码，UNKNOWN 时也保留。',
    'source_status_message': '源端委托状态说明。',
    'strategy_name': '策略名称，透传源端。',
    'correlation_ref': '应用关联备注，最多 24 个 ASCII 字节；不提供幂等保证。',
    'source_code': '源端提交或撤单的返回码。',
    'cancelable_only': '是否只查询源端判定为可撤的委托。',
    'target': '撤单目标；按桥接委托标识或市场+交易所委托标识二选一。',
    'task_id': '当前服务进程中的任务标识；不是跨重启持久任务。',
    'total': '总数；类型允许 null 时表示源端未提供。',
    'finished': '已完成数量；null 表示未提供。',
    'completed_at': '终态完成时间，含时区；任务未结束时为 null。',
    'progress': '源端下载进度；尚未收到时为 null。',
    'result': '固定为 null；下载结果保存在源端缓存，通过查询 API 读取。',
    'pending': '排队中的任务数。',
    'running': '执行中的任务数。',
    'completed': '已完成的任务数。',
    'failed': '失败的任务数。',
    'connected': 'Trader 当前是否已连接；RPC 可用不代表此字段为 true。',
    'trader_available': 'Trader 对象是否已创建，不等于已连接。',
    'last_heartbeat': '最近成功心跳时间；未取得时为 null。',
    'heartbeat_failures': '心跳失败次数；不可用时为 null。',
    'reconnect_attempts': '重连尝试次数；不可用时为 null。',
    'consecutive_failures': '连续连接失败次数；不可用时为 null。',
    'uptime_seconds': '服务运行秒数；不可用时为 null。',
    'connection_state': '连接生命周期状态，允许值见类型。',
    'last_connection_error': '最近连接错误说明；无错误时为 null。',
    'next_retry_at': '计划的下一次重连时间；未安排时为 null。',
    'active_clients': '当前连接客户端数量。',
    'download_tasks': '下载任务数量统计。',
    'package_version': '服务端 qmt-rpyc 安装包版本。',
    'protocol_version': '传输认证协议版本。',
    'available': '当前 SDK 是否满足该 API 的适配要求；不是行情新鲜度保证。',
    'adapter_id': '选中的源端适配实现标识；不可用时可为 null。',
    'operations': '完整 API 名称到适配可用性说明的映射。',
    'tables': '需要的财务表名，非空且不可重复；默认全部固定表。',
    'date_basis': '财务查询日期口径：report_time 报告期，announce_time 公告期。',
    'm_timetag': '财务报告期日期。',
    'm_anntime': '财务公告日期。',
    'declareDate': '源端公告日期。',
    'endDate': '源端报告期结束日期。',
    'tot_assets': '资产总计；源端数值，缺失为 null。',
    'tot_liab': '负债合计；源端数值，缺失为 null。',
    'tot_shrhldr_eqy_excl_min_int': '归属母公司股东权益；源端数值，缺失为 null。',
    'total_equity': '所有者权益合计；源端数值，缺失为 null。',
    'cap_stk': '实收资本/股本；源端数值，缺失为 null。',
    'revenue': '营业收入；源端数值，缺失为 null。',
    'oper_profit': '营业利润；源端数值，缺失为 null。',
    'net_profit_excl_min_int_inc': '归属母公司净利润；源端数值，缺失为 null。',
    's_fa_eps_basic': '基本每股收益；源端数值，缺失为 null。',
    's_fa_eps_diluted': '稀释每股收益；源端数值，缺失为 null。',
    'net_cash_flows_oper_act': '经营活动现金流量净额；源端数值，缺失为 null。',
    'net_cash_flows_inv_act': '投资活动现金流量净额；源端数值，缺失为 null。',
    'net_cash_flows_fnc_act': '筹资活动现金流量净额；源端数值，缺失为 null。',
    'cash_cash_equ_end_period': '期末现金及现金等价物；源端数值，缺失为 null。',
    'total_capital': '总股本；源端数值，缺失为 null。',
    'circulating_capital': '流通股本；源端数值，缺失为 null。',
    'restrict_circulating_capital': '限售股本；源端数值，缺失为 null。',
    'freeFloatCapital': '自由流通股本；源端数值，缺失为 null。',
    'shareholder': '股东总户数；源端数值，缺失为 null。',
    'shareholderA': 'A 股股东户数；源端数值，缺失为 null。',
    'shareholderB': 'B 股股东户数；源端数值，缺失为 null。',
    'shareholderH': 'H 股股东户数；源端数值，缺失为 null。',
    'shareholderFloat': '流通股股东户数；源端数值，缺失为 null。',
    'shareholderOther': '其他股东户数；源端数值，缺失为 null。',
    'ratio': '持股比例；保留源端比率及单位，不转换为百分数。',
    'rank': '源端持股排名；缺失为 null。',
    's_fa_bps': '每股净资产；源端数值，缺失为 null。',
    's_fa_ocfps': '每股经营现金流；源端数值，缺失为 null。',
    'du_return_on_equity': '净资产收益率；源端比率，不换算单位。',
    'gear_ratio': '资产负债率；源端比率，不换算单位。',
}

for _name, _description in {
    'Balance': '资产负债表', 'Income': '利润表', 'CashFlow': '现金流量表',
    'Capital': '股本表', 'HolderNum': '股东户数表', 'Top10Holder': '十大股东表',
    'Top10FlowHolder': '十大流通股东表', 'PershareIndex': '每股指标表',
}.items():
    FIELD_DESCRIPTIONS[_name] = _description + '记录；未请求时为 null，请求后无记录为空数组；字段保留源端单位。'

FIELD_OVERRIDES = {
    ('OptionChainRequest', 'expiry_date'): '到期日，不能早于服务端上海市场日期（含今天）；仅发现当前合约，不支持历史目录。',
    ('OptionContract', 'expiry_date'): '期权合约实际到期日，YYYY-MM-DD。',
    ('MarketTicks', 'items'): '按合约代码去重、升序的市场报价或逐项失败结果。',
    ('KnownDate', 'value'): '有效日期，YYYY-MM-DD。',
    ('DownloadStatus', 'status'): 'pending 排队、running 执行、completed SDK 正常返回、failed 失败；completed 不保证覆盖率或新鲜度。',
    ('DownloadStatus', 'error'): '失败任务的结构化错误；非失败状态固定为 null。',
    ('DownloadProgress', 'instrument'): '当前下载的合约代码；未提供时为 null。',
    ('Top10HolderRecord', 'quantity'): '源端持股数量；不改变单位，缺失为 null。',
    ('Top10FlowHolderRecord', 'quantity'): '源端流通持股数量；不改变单位，缺失为 null。',
    ('Order', 'status'): '归一化委托状态；UNKNOWN 时检查 source_status，不推断成交或撤单。',
}


def field_description(model, field):
    override = FIELD_OVERRIDES.get((model, field))
    return override if override is not None else FIELD_DESCRIPTIONS[field]
