"""Build a standalone Python 3.6 QMT strategy from the owned bridge modules."""
import ast
import hashlib
from importlib.resources import files

from qmt_rpyc.version import __version__
from .winpipe import DEFAULT_PIPE, pipe_path

MODULES = ('financial_wire.py', 'bridge_debug.py', 'bridge_trading.py', 'bridge_runtime.py', 'bridge_queue.py', 'winpipe.py')
ENTRY = '''

# Trading uses the account supplied in each authenticated request.
PIPE_NAME = "qmt_rpyc_bridge_v1"
_service = None
_bridge = None


def init(ContextInfo):
    global _service, _bridge
    from datetime import datetime, timedelta
    if _service is not None:
        raise RuntimeError("Bridge already initialized; stop the previous strategy")
    _bridge = BridgeQueue(StrategyRuntime(ContextInfo, globals()))
    _service = PipeServer(PIPE_NAME, _bridge)
    try:
        start = (datetime.now() + timedelta(seconds=1)).strftime("%Y-%m-%d %H:%M:%S")
        ContextInfo.run_time("bigqmt_bridge_pump", "100nMilliSecond", start)
        _service.start()
    except Exception:
        stop(ContextInfo)
        raise
    print("QMT_RPYC_BRIDGE ready; version=" + RELEASE_VERSION + "; build=" + STRATEGY_BUILD + "; read_only=False")


def bigqmt_bridge_pump(ContextInfo):
    if _service is None or _bridge is None:
        return
    # Pipe I/O and business dispatch share this callback: QMT schedules
    # background Python threads too rarely to carry a round trip. An
    # unhandled exception can stop the whole strategy, so it never propagates.
    try:
        _service.poll()
        _bridge.pump()
        _service.poll()
    except Exception:
        import traceback
        traceback.print_exc()


def handlebar(ContextInfo):
    pass


def stop(ContextInfo):
    global _service, _bridge
    if _service is not None:
        _service.stop()
    _service, _bridge = None, None
    print("QMT_RPYC_BRIDGE stopped; pending_handles_retained=" + str(reap()))
'''


def build(pipe_name=DEFAULT_PIPE):
    pipe_path(pipe_name)
    entry = ENTRY.replace('PIPE_NAME = "qmt_rpyc_bridge_v1"', "PIPE_NAME = " + ascii(pipe_name), 1)
    parts = ['# coding: gbk\n# QMT 策略文件：使用 GBK 编码。\n# Generated by qmt-rpyc; edit the source modules.\n']
    for name in MODULES:
        source = files(__package__).joinpath(name).read_text(encoding='utf-8')
        lines = source.splitlines(keepends=True)
        tree = ast.parse(source)
        for node in reversed(tree.body):
            if isinstance(node, ast.ImportFrom) and node.level:
                del lines[node.lineno - 1:node.end_lineno]
        parts.append('\n# ---- ' + name + ' ----\n' + ''.join(lines))
    parts.insert(1, 'RELEASE_VERSION = ' + repr(__version__) + '\n')
    source = '\n'.join(parts) + entry
    # Deterministic fingerprint of the generated source before adding itself.
    digest = hashlib.sha256(source.encode('gbk')).hexdigest()[:16]
    parts.insert(2, 'STRATEGY_BUILD = ' + repr(digest) + '\n')
    source = '\n'.join(parts) + entry
    ast.parse(source, feature_version=(3, 6))
    return source
